#!/bin/bash

[ -z "$1" ] && exit 1

cask exec emacs -Q -nw                                                           \
     -l xquery-mode.el                                                           \
     -l test/xquery-mode-test.el                                                 \
     test/$1.xqy                                                                 \
     --eval "(ert-run-tests-batch \"test-xquery-mode-indent-$1\")"               \
     --eval "(ediff-buffers \"$1.xqy\" \"*fixture-$1*\")"                        \
     --eval '(with-current-buffer "*Ediff Control Panel*" (ediff-toggle-split))' \
     --eval "(load-theme 'tango-dark)"                                           \
     --eval '(setq-default truncate-lines t)'
